Port = 8080

# Gateways defines the list of gateways that will be used by this proxy
Gateways = [
    {URL="http://127.0.0.1:8079", EpochStart="0", EpochEnd="latest", NonceStart="0", NonceEnd="latest", Name="R640"},
]

# ClosedEndpoints defines the list of closed endpoints that the proxy will specifically not serve
ClosedEndpoints = [
    "/transaction/send",
    "/transaction/send-multiple",
    "/transaction/send-user-funds"
]

# AccessKeys defines the keys that are allowed to use this proxy
AccessKeys = [
    {Key="", Alias="ALL"}
]

# Redis configuration for metrics storage
[Redis]
    Enabled = false
    URL = "127.0.0.1:6379"
