// This file is auto-generated by the build system
// It re-exports the contract for WASM compilation

use multiversx_sc_wasm_adapter::*;

use requests_contract::*;

pub struct ContractBuilder;

impl ContractBuilder {
    pub fn contract_obj<'a>() -> Box<dyn ContractBase + 'a> {
        Box::new(RequestsContract {})
    }
}

pub fn contract_obj_builder() -> ContractBuilder {
    ContractBuilder
}
